PX4/NuttX branch test: master
NuttX:
 - https://github.com/PX4-NuttX/nuttx/tree/master
 - https://github.com/PX4-NuttX/nuttx/commit/afead9c9da321cf5eb642662db52e3597ff62781

Changes from PX4/NuttX (https://github.com/PX4/NuttX/commit/7fffab1610d2ea08a95383febd0579e0037b6b51) in current PX4/master (75054f11df8f995922335355cba341bd32ad1774)
https://github.com/PX4/NuttX/compare/7fffab1610d2ea08a95383febd0579e0037b6b51...afead9c9da321cf5eb642662db52e3597ff62781

afead9c9da (HEAD, origin/master) arch: arm: a1x: nxstyle fixes for a1x arch
f706f5e0e8 boards/imxrt1060-evk: Generate nuttx.map in the root directory
2810220ea9 Update defconfig per refresh.sh report
090a4d1690 Update .gitignore per testbuild.sh report
816f624819 tools/Makefile.host: Initialize Q by inspecting V
95e5506637 tools/testbuild.sh: Verify nuttx/apps folder clean after build
48e6b97ca7 tools/testbuild.sh: Check defconfig in the canonical format
c153c31fbd tools/refresh.sh: Save defconfig and exit with 1 only when the difference exist
5c1497aeb1 tools: Remove the temp variable in checking program exit code
cf674ed51c checkpatch.sh: Simplify the code logic, no functional change

Apps:
 - https://github.com/PX4/NuttX-apps/tree/master
 - https://github.com/PX4/NuttX-apps/commit/63288eb81fd57b7778e0d8fe804ac6a5a3f5751f

Changes from PX4/NuttX-apps (https://github.com/PX4/NuttX-apps/commit/95e105548a2037f42bf2f13b214ae083b921ff03) in current PX4/master (75054f11df8f995922335355cba341bd32ad1774)
https://github.com/PX4/NuttX-apps/compare/95e105548a2037f42bf2f13b214ae083b921ff03...63288eb81fd57b7778e0d8fe804ac6a5a3f5751f

63288eb8 (HEAD -> master, origin/master) fix apps/include/graphics/nxwidgets/cwidgetcontrol.hxx:550:20: error: ‘m_xyinput’ was not declared in this scope
68ed2a2a build.yaml: Change arm-11 to arm-12
0c84e22a example: Remove all APPNAME from Makefile
4431d770 .gitignore: Add more entries found during prcheck testing
a82d74b8 nshlib: Call BOARDIOC_FINALINIT in nsh_telnetstart if CONFIG_NSH_CONSOLE not define
b1b45de3 Revert "nshlib: Move BOARDIOC_FINALINIT into nsh_initscript"
650b58d6 nshlib: Fix nxstyle warning
de8a56d1 nshlib: Split shell functionality from nsh to sh
3f930256 nshlib: Enhance nsh to execute the shell script
d307758c nshlib: Rename 'sh' command to 'source' command